[tool.poetry]
name = %name%
version = "0.1.0"
description = ""
authors = ["AppleDannyClegg <jives.gimbals0@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

